name: Deploy DAB to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bundle-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate bundle
        working-directory: .
        run: databricks bundle validate -t prod
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}

      - name: Deploy bundle
        working-directory: .
        run: databricks bundle deploy -t prod
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}
